# Numpy Assignment

###### [1] Numpy stands for ?

> NumPy, which stands for Numerical Python,
is a library consisting of multidimensional array objects.
Using NumPy, mathematical and logical operations on arrays can be performed

###### [2] The most important object defined in NumPy is an N-dimensional array type called ?

> ndarray

##### [3] What will be the output for following code ?

In [1]:
import numpy as np
a=np.array([1,2,3],dtype=complex)
print(a)
a=np.array([1,2,3])
print(a)
a=np.array([1,2,3],dtype=float)
print(a)
print('\n')


a=np.dtype('i4')
print(a)
a=np.array([1,2,3,4,5],ndmin=2)
print(a)
print('\n')


dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)],dtype = dt)
print(a['age'])

[1.+0.j 2.+0.j 3.+0.j]
[1 2 3]
[1. 2. 3.]


int32
[[1 2 3 4 5]]


[10 20 30]


In [2]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
c = c*a
print (c[2])

21


In [3]:
a = np.array([1,2,3,5,8])
a = a + 1
print (a[1])

3


In [4]:
a = np.array([[1,2,3],[0,1,4]])
print(a.size)
a = np.array([1,2,3,5,8])
print(a.ndim)
print("'a.ndim.describe' throws an error as 'int' object has no attribute 'describe'\n")

print("'a.describe' throws an error as 'numpy.ndarray' object has no attribute 'describe'\n")

print("'a.shape()' throws an error as 'tuple' object is not callable\n")

print(a.shape)

6
1
'a.ndim.describe' throws an error as 'int' object has no attribute 'describe'

'a.describe' throws an error as 'numpy.ndarray' object has no attribute 'describe'

'a.shape()' throws an error as 'tuple' object is not callable

(5,)


In [5]:
a=np.array([[1,2,3],[0,1,4]])
b=np.zeros((2,3),dtype=np.int16)
c=np.ones((2,3),dtype=np.int16)
d=a+b+c
print(d[1,2])
print(d.size)

print("\n'd.attributes' throws an error as 'numpy.ndarray' object has no attribute 'attributes'\n")

print("'a.zeroes()' throws an error as 'numpy.ndarray' object has no attribute 'zeros'")

5
6

'd.attributes' throws an error as 'numpy.ndarray' object has no attribute 'attributes'

'a.zeroes()' throws an error as 'numpy.ndarray' object has no attribute 'zeros'


###### [4] Find rank,determinant,trace,inverse,transpose of 
     A=np.array([[6,1,1],[4,-2,5],[2,8,7]])

In [6]:
A=np.array([[6,1,1],[4,-2,5],[2,8,7]])
print("The given matrix A is:\n",A)
print("The rank of A is:",np.linalg.matrix_rank (A))
print("The determinant of A is:",np.linalg.det(A))
print("The trace of A is:",np.trace(A))
print("The inverse of A is:\n",np.linalg.inv(A))
print("The transpose of A is:\n",np.transpose(A))

The given matrix A is:
 [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
The rank of A is: 3
The determinant of A is: -306.0
The trace of A is: 11
The inverse of A is:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
The transpose of A is:
 [[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


###### [5] Type these lines of code and check the output for each of them.

In [7]:
X=[1,2,3,4,5,6]
Y=[10,9,8,7,6,5]
print("X+Y is:",X+Y)
print("\n'*','%','/','-','^' are unsupported operand types for LIST and LIST")

X+Y is: [1, 2, 3, 4, 5, 6, 10, 9, 8, 7, 6, 5]

'*','%','/','-','^' are unsupported operand types for LIST and LIST


###### [6] Type these lines of code and check the output for each of them.

In [8]:
list1 = np.array([1, 2, 3, 4 ,5, 6])
list2 = np.array([10, 9, 8, 7, 6, 5])


In [9]:
list1*list2

array([10, 18, 24, 28, 30, 30])

In [10]:
list1+list2

array([11, 11, 11, 11, 11, 11])

In [11]:
list1%list2

array([1, 2, 3, 4, 5, 1], dtype=int32)

In [12]:
list1/list2

array([0.1       , 0.22222222, 0.375     , 0.57142857, 0.83333333,
       1.2       ])

In [13]:
list1-list2

array([-9, -7, -5, -3, -1,  1])

In [14]:
list1^list2

array([11, 11, 11,  3,  3,  3], dtype=int32)